### PR TITLE
Fix linter issues

### LINKED ISSUE #20: Fix issues detected by linters
https://github.com/YetAnotherSpieskowcy/travel-agency-app/actions/runs/8662602509/job/23754880076?pr=14

### PR DESCRIPTION
**Pull request by Jackenmen**
Fixes #20

### CODE REVIEW

File: api_gateway/src/main/kotlin/pl/edu/pg/rsww/apigateway/RoutingController.kt [hunk 1]
```diff
@@ -21,6 +20,11 @@ public class RoutingController(
     @Autowired
     private val template: RabbitTemplate,
 ) {
+    @RequestMapping("/api")
```
Comment (bstrzelecki) [inline api_gateway/src/main/kotlin/pl/edu/pg/rsww/apigateway/RoutingController.kt:23]: Maybe /health or equivalent?

**Review by bstrzelecki — APPROVED** [review]

**Review by BognaLew — APPROVED** [review]
